FROM node:20-alpine AS build
WORKDIR /app


COPY package*.json ./


RUN npm ci


COPY . .

FROM node:20-alpine AS production
WORKDIR /app


ENV NODE_ENV=production


COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/*.js ./


USER node


EXPOSE 5000

CMD ["node", "server.js"]
